### PR TITLE
Fix pip install path issue for certain packages

### PR DESCRIPTION
**Pull request by xuechendi**
Fix relative path import.

Error Log before fixing:
image

After adding complete path, I am able to run serving.

## 1. install steps
```
conda create -n llm-on-ray python=3.9
conda activate llm-on-ray
pip install .[cpu,ui] -f https://developer.intel.com/ipex-whl-stable-cpu -f https://download.pytorch.org/whl/torch_stable.html
source $(python -c "import oneccl_bindings_for_pytorch as torch_ccl;print(torch_ccl.cwd)") /env/setvars.sh

# Ray Started
```

## 2. test step:
```
python inference/serve.py --config_file inference/models/llama-2-7b-chat-hf.yaml
```

### CODE REVIEW

**Comment by xuechendi** [comment]
@carsonwang @KepingYan , please help to take a review.

**Comment by xwu99** [comment]
@KepingYan 

From https://docs.python.org/3/library/sys.html#sys.path

python script.py command line: prepend the script’s directory. If it’s a symbolic link, resolve symbolic links.

We should test and make sure it works in the following both cases and should allow the script to be run from any path:
1) user installed the whole package and run serve.py.
2) user only installed the dependencies and run serve.py directly.

**Comment by xuechendi** [comment]
> @KepingYan
> 
> From https://docs.python.org/3/library/sys.html#sys.path
> 
> python script.py command line: prepend the script’s directory. If it’s a symbolic link, resolve symbolic links.
> 
> We should test and make sure it works in the following both cases and should allow the script to be run from any path:
> 
> 1. user installed the whole package and run serve.py.
> 2. user only installed the dependencies and run serve.py directly.

Yeah, after all, the readme should provide User a smooth experience to Run a 'hello world' demo.
If adding my cloned llm-on-ray to python path is a must, may need to add it to README as well.
Otherwise, provide full module path during import will help to avoid python package finding issues.

**Comment by xwu99** [comment]
We also need to consider the distributed nature of Ray that all workers should find the package. (may be the cause of this issue)

Following the industrial practices, I would suggest move inference/finetune into a package `llm_on_ray` namespace and use absolute module path to import module, in this way, ui/inference/finetune can cross import as well.  

For developers, they can use pip install -e to install package in-place and debug.

**Comment by xwu99** [comment]
@KepingYan  could you fix this in #79 as discussed?

**Comment by xuechendi** [comment]
@xwu99 , That sounds great! This is also something I felt quite unusual that after installing llm-on-ray, the package name is not "llm-on-ray" but "inference". Great to know that you are going to fix the package name. :)

Please feel free to close this PR once you have merge the other one. I would be willing to test the new installation by then.

**Comment by xwu99** [comment]
fixed by #106

**Pull request closed without merging**
