### PR TITLE
Added the Application based on the LLM-on-Ray Service

### PR DESCRIPTION
**Pull request by tianyil1**
This PR is updated with the followings:
- added the application framework
- added the two applications: basic chatbot and text2sql chatbot.

which is tested well in my local env, please help review and merge. Thanks.

### CODE REVIEW

**Comment by carsonwang** [comment]
@tianyil1 Thanks for the PR! Please add license header to the python files similar to other files in the project. Also appreciate if you can update the description to let us know which applications will be included in this PR and if it is ready to merge or there are additional todos.

**Comment by tianyil1** [comment]
> @tianyil1 Thanks for the PR! Please add license header to the python files similar to other files in the project. Also appreciate if you can update the description to let us know which applications will be included in this PR and if it is ready to merge or there are additional todos.

Thanks for your suggestions. I have refined the license header and added the description with future applications, and it's ready for merging. @carsonwang

**Review by carsonwang — APPROVED** [review]
Thanks for adding the applications. Merging this.

**Comment by carsonwang** [comment]
Merging this caused a few dependabot alerts and I have merged all the fixes. Please checked the updated requirements.txt.

**Pull request merged**
